export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: 'Nuxt3 AI企业级开发实战指南',
      description: '全面掌握Nuxt3 + AI技术栈，从基础到企业级实战的完整学习路径。涵盖Vue3、TypeScript、AI集成、性能优化等核心技术。',
      ogImage: '/hero.png',
      ogImageComponent: 'ShadcnDocs',
      ogImageColor: 'light',
      umami: {
        enable: true,
        src: 'https://cloud.umami.is/script.js',
        dataWebsiteId: 'd793fbf3-461e-4e26-9ec9-4e9141df96ee',
      },
    },
    theme: {
      customizable: true,
      color: 'vue',
      radius: 0.5,
    },
    banner: {
      enable: true,
      showClose: true,
      content: '🚀 **全新升级** - Nuxt3 AI企业级开发实战指南现已发布！',
      to: '/getting-started/introduction',
      target: '_self',
      border: true,
    },
    header: {
      title: 'Nuxt3 AI实战指南',
      showTitle: true,
      logo: {
        light: '/logo.svg',
        dark: '/logo-dark.svg',
      },
      border: false,
      darkModeToggle: true,
      languageSwitcher: {
        enable: true,
        triggerType: 'icon',
        dropdownType: 'select',
      },
      nav: [{
        title: '文档',
        links: [{
          title: '快速开始',
          to: '/getting-started',
          description: '快速搭建你的第一个Nuxt3 AI应用',
          icon: 'lucide:rocket',
        }, {
          title: '组件库',
          to: '/components/prose',
          description: '探索丰富的UI组件和使用示例',
          icon: 'lucide:box',
        }, {
          title: 'API文档',
          to: '/api/configuration/shadcn-docs',
          description: '深入了解配置选项和API接口',
          target: '_self',
          icon: 'lucide:code',
        }],
      }, {
        title: 'AI技术',
        links: [{
          title: 'AI集成指南',
          to: '/ai/integration',
          description: '学习如何在Nuxt3中集成AI技术',
          target: '_self',
        }, {
          title: '智能组件',
          to: '/ai/components',
          description: '使用AI驱动的智能组件',
          target: '_self',
        }, {
          title: '性能优化',
          to: '/ai/optimization',
          description: 'AI应用的性能调优策略',
          target: '_self',
        }],
      },
      // {
      //   title: '实战案例',
      //   links: [{
      //     title: '企业级项目',
      //     to: '/examples/enterprise',
      //     description: '真实企业级项目开发案例',
      //     target: '_self',
      //   }, {
      //     title: 'AI应用场景',
      //     to: '/examples/ai-scenarios',
      //     description: '常见AI应用场景实现',
      //     target: '_self',
      //   }],
      // },
      {
        title: '博客',
        to: '/blog',
        target: '_self',
        showLinkIcon: false,
      }],
      links: [
        {
          icon: 'lucide:book-open',
          to: '/getting-started/introduction',
          target: '_self',
        },
        {
          icon: 'lucide:github',
          to: 'https://github.com/your-username/nuxt3-ai-guide',
          target: '_blank',
        },
      ],
    },
    aside: {
      useLevel: true,
      levelStyle: 'aside',
      collapse: false,
      collapseLevel: 1,
      folderStyle: 'default',
    },
    main: {
      padded: true,
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: true,
      codeCopyIcon: 'lucide:clipboard',
      editLink: {
        enable: true,
        pattern: 'https://github.com/your-username/nuxt3-ai-guide/edit/main/www/content/:path',
        text: '编辑此页面',
        icon: 'lucide:square-pen',
        placement: ['docsFooter'],
      },
      backToTop: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'css': 'vscode-icons:file-type-css',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-light-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
      },
    },
    footer: {
      credits: '© 2024 Nuxt3 AI企业级开发实战指南. 专注于现代化前端开发技术分享.',
      links: [
        {
          icon: 'lucide:book-open',
          title: '学习指南',
          to: '/getting-started/introduction',
          target: '_self',
        },
        {
          icon: 'lucide:cpu',
          title: 'AI技术',
          to: '/ai/integration',
          target: '_self',
        },
        {
          icon: 'lucide:users',
          title: '社区讨论',
          to: 'https://github.com/your-username/nuxt3-ai-guide/discussions',
          target: '_blank',
        },
        {
          icon: 'lucide:github',
          to: 'https://github.com/your-username/nuxt3-ai-guide',
          target: '_blank',
        },
      ],
    },
    toc: {
      enable: true,
      enableInMobile: true,
      enableInHomepage: false,
      title: '本页目录',
      links: [
        {
          title: '⭐ Star支持',
          icon: 'lucide:star',
          to: 'https://github.com/your-username/nuxt3-ai-guide',
          target: '_blank',
          showLinkIcon: true,
        },
        {
          title: '💬 问题反馈',
          icon: 'lucide:circle-dot',
          to: 'https://github.com/your-username/nuxt3-ai-guide/issues',
          target: '_blank',
          showLinkIcon: true,
        },
      ],
      iconLinks: [
        {
          icon: 'lucide:book-open',
          to: '/getting-started/introduction',
          target: '_self',
        },
        {
          icon: 'lucide:cpu',
          to: '/ai/integration',
          target: '_self',
        },
        {
          icon: 'lucide:users',
          to: 'https://github.com/your-username/nuxt3-ai-guide/discussions',
          target: '_blank',
        },
        {
          icon: 'lucide:github',
          to: 'https://github.com/your-username/nuxt3-ai-guide',
          target: '_blank',
        },
      ],
      carbonAds: {
        enable: false,
        disableInDev: true,
        disableInMobile: false,
        fallback: false,
        fallbackMessage: 'Please support us by disabling your ad blocker.',
        code: 'CW7ITKJN',
        placement: 'shadcn-docs-nuxtvercelapp',
        format: 'cover',
      },
    },
    search: {
      enable: true,
      inAside: false,
      style: 'input',
    },
    data: {},
  },
});
